### ISSUE TITLE
The error message Function register_post_type was called incorrectly. Post type names must be between 1 and 20 characters in length. (paygate_standalone_order)

### ISSUE THREAD

**Issue by ghost** [PayGate/PayWeb_Wordpress_Standalone#5]
The name you use as the first argument in register_post_type() must be between 1 and 20 characters long. Post type key. Must not exceed 20 characters and may only contain lowercase alphanumeric characters, dashes, and underscores. Ref "https://developer.wordpress.org/reference/functions/register_post_type/"

In paygate-standalone-wp-plugin/paygate-standalone-wp-plugin.php 45 line (paygate_standalone_order) need to short.
![Screenshot from 2024-09-03 11-51-13](https://github.com/user-attachments/assets/d546c001-ef81-43cb-9df4-da401e309f80)

@appinlet #

**Comment by bruce-atkinson** [comment]
@subhankara this issue is fixed in v1.0.3 https://github.com/Paygate/PayWeb_WordPress_Standalone/pull/6

**Comment by ghost** [comment]
Thanks,

Best Regards,

*Subhankar Acharjee*

*Tech Lead*Skype - ***@***.***
------------------------------
Capital Numbers | Skillsz
Download Fact Sheet
<https://drive.google.com/file/d/1uW0tqLakI-lMip5dy1S4bGB_eAMq0pDX/view>

This e-mail and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this e-mail in error please notify the system manager.
This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system. If you are not the intended recipient
you are notified that disclosing, copying, distributing, or taking any
action in reliance on the contents of this information is strictly
prohibited.
